version: '2.2'

services:
  code:
    image: "async_chat"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - 5050:5050
    depends_on:
        - redis

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379

